// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Speet.Models;

namespace Speet.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210930101929_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Speet.Models.SportGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeetupDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("NumberOfParticipants")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SportGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
